projects:
    -
        name: p0dxd/website
        path: front-end
        version: 1.0.0
        stages:
            build:
                tool: node
                version: latest
            upload:
                tool: docker
                version: ~
    -
        name: p0dxd/website-backend
        path: back-end
        version: 1.0.0
        stages:
            build:
                tool: gradle
                version: 6.2.1
            upload:
                tool: docker
                version: ~