#This file fill contain configuration to run a docker inside a machine
#Main reason for extracting it is allowing for a dynamic run of an application container
#while also mantaining security and only allowing whats inside this file to be executed with checks
#for common exploits and ways of obtaining information
#if it starts with $ it will be transfered from container machine
#iff that application is allowed to access those specific details
#else anyone could create a simple app that asks for them and prints the value
docker:
    -
        command: run
        arguments:
            config_options: '-itd' 
            ports:
                - 49160:49160
            environment:
                GITHUB_TOKEN: '$GITHUB_TOKEN'
                KEYSTORE_ALIAS: '$KEYSTORE_ALIAS'
                KEYSTORE_PASSWORD: '$KEYSTORE_PASSWORD'
                SPRING_PROFILES_ACTIVE: prod
                KEYSTORE: '$PRIVATE_KEY_P12'
                KEYSTORE_JAVA_TYPE: '$KEYSTORE_JAVA_TYPE'


